POST http://localhost:5001/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NGE0ZGI0ZGRlYTIzMjA2N2RjMTk2NiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzY3ODU1ODgyLCJleHAiOjE3Njc5NDIyODJ9.gGYxZUvAP7w795v4hPg3poJqOi9tLW7ktUgMwDj7Oq8
Content-Type: application/json

{
  "items": [
    {
      "product": "694a49797fe71474fe4522e5",
      "quantity": 2,
      "price": 10000
    }
  ],
    "phone": "99119191",
      "address": "UB bZD",
  "totalAmount": 20000,
  "paymentMethod": "card"
}