POST http://localhost:5001/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NGE0MWU2MTAwNWNiYWUyODFmMWY4YSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NjgxOTM1NiwiZXhwIjoxNzY2OTA1NzU2fQ.tzUvPgalyHc0Tc7GUFr-0anKqel6mlHORhEi-UtIIx8
Content-Type: application/json

{
  "items": [
    {
      "product": "694a49797fe71474fe4522e5",
      "quantity": 2,
      "price": 10000
    }
  ],
    "phone": "99119191",
      "address": "UB bZD",
  "totalAmount": 20000,
  "paymentMethod": "card"
}
