DELETE http://localhost:5001/api/products/694a4889842d66ec29141e72
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NGE0ZGI0ZGRlYTIzMjA2N2RjMTk2NiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzY2NTUxMjU5LCJleHAiOjE3NjY2Mzc2NTl9.8Jrx9jGMtnEC_YKmlHEWE2duvN3YNBkDFsXnEDwrNAM
